# Generated by Django 5.2.15 on 2026-06-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=40)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('source_uid', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('source_slug', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('range', models.PositiveSmallIntegerField()),
                ('attacks', models.FloatField()),
                ('attacks_string', models.CharField(max_length=40)),
                ('ap', models.PositiveSmallIntegerField(default=0)),
                ('special_rules', models.JSONField(blank=True, default=dict)),
                ('source_uid', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quality', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('tough', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('special_rules', models.JSONField(blank=True, default=dict)),
                ('source_uid', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='army_books.faction')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UnitWeaponSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True)),
                ('upgrade_cost', models.IntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_slots', to='army_books.unit')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_slots', to='army_books.weapon')),
            ],
            options={
                'ordering': ('unit__name', 'weapon__name'),
            },
        ),
    ]
