# Generated by Django 5.2.15 on 2026-06-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('army_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('point_limit', models.PositiveIntegerField(default=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army_lists', to='army_books.faction')),
            ],
            options={
                'ordering': ('-updated_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ListUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('army_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='lists.armylist')),
                ('selected_weapon_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_entries', to='army_books.unitweaponslot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entries', to='army_books.unit')),
            ],
            options={
                'ordering': ('unit__name', 'id'),
            },
        ),
    ]
